### PR TITLE
why no workie

### PR DESCRIPTION
**Pull request by jtslear**
@rszewczyk, I have a question for you.

* I've updated the tests to include the new desired output, a JSON formatted output with two objects, `version` and `special_var`
* Why is the JSON encoding not working like I expect it too?  If you run `go test -v` you see the output is nil
* This app still compiles and starts up fine, and if you do a curl, you get an empty JSON object back.
* Can you provide me some assistance?

### CODE REVIEW

**Comment by rszewczyk** [comment]
The standard library's `"encoding/json"` package relies on reflection, so when you marshal a struct, it can only see public (i.e. those with capitalized names) fields. 

If your intent is to have the `json` representation have lower case field names, you can use struct tags.

**Comment by rszewczyk** [comment]
for example:
```
type Response struct {
        Version       int      `json:"version"`
        Special_var string `json:"special_var"`
}
```

**Comment by jtslear** [comment]
THANKS, now that worked.  But testing it does not....  Give it a shot if you can.

**Comment by rszewczyk** [comment]
It looks like you still have some lower case struct fields. You want your output struct to look something like:

```
var HTTPOutput struct {
	Version    int
	SpecialVar string
}
```

**Comment by jtslear** [comment]
@rszewczyk I made some changes, but the tests still fail:
```
6s testapp more-features % go test -v
=== RUN   TestOutputVersion
--- FAIL: TestOutputVersion (0.00s)
        helloweb_test.go:17: Status Code: %s 200
        helloweb_test.go:32: Body: %s
        helloweb_test.go:33: Version: %d 0
        helloweb_test.go:34: Special Variable: %s
        helloweb_test.go:37: Version is not 11, got 0
        helloweb_test.go:44: Special Var is not ninety-nine, got
FAIL
exit status 1
FAIL    github.com/jtslear/testapp      0.014s
```

**Pull request closed without merging**
